name: Publish

on:
  release:
    types: [created]

env:
  PYTHON_VERSION: "3.9"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install poetry poetry-dynamic-versioning twine
      - name: Install dependencies
        run: |
          poetry install
      - name: Build
        run: |
          poetry build
      - name: Publish
        run: |
          poetry publish --username __token__ --password ${PYPI_API_TOKEN}
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
