name: Test

on:
  push:

env:
  PYTHON_VERSION: "3.9"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint
        run: |
          make lint-nofix

  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Type check
        run: |
          make type-nocache

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Test
        run: |
          make test-nocache
